apiVersion: v1
kind: Pod
metadata:
  name: command-pod
  namespace: the-kubernetes-workshop
spec:
  containers:
  - name: container-with-command
    image: debian@sha256:26f98ccd92fd0a44d6928ce8ff8f4921b4d2f535bfa07555ee5d18f61429cf0c
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
    command:
    - /bin/bash
    - -ec
    - while :; do echo '.'; sleep 5; done
