kind: Pod
apiVersion: v1
metadata:
  name: k8s-for-beginners
spec:
  containers:
    - name: k8s-for-beginners
      image: k8s-for-beginners:v0.0.1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: true
